[package]
name = "rustmatheval"
version = "0.1.0"
authors = ["George-Lewis <georgejeffreylewis@gmail.com>"]
edition = "2018"
description = "A library for evaluating mathematical statements"
license = "MIT"

[dependencies]
# None!